/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DietEntry = IDL.Record({
  'id' : IDL.Nat,
  'fat' : IDL.Nat,
  'carbs' : IDL.Nat,
  'calories' : IDL.Nat,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'protein' : IDL.Nat,
});
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const Exercise = IDL.Record({
  'id' : IDL.Nat,
  'difficulty' : Difficulty,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'targetReps' : IDL.Nat,
  'category' : IDL.Text,
});
export const ExerciseCategory = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const WorkoutExercise = IDL.Record({
  'name' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'notes' : IDL.Text,
});
export const WorkoutPlan = IDL.Record({
  'id' : IDL.Nat,
  'exercises' : IDL.Vec(WorkoutExercise),
  'description' : IDL.Text,
  'dayLabel' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Time = IDL.Int;
export const Battle = IDL.Record({
  'status' : IDL.Variant({
    'active' : IDL.Null,
    'finished' : IDL.Null,
    'waiting' : IDL.Null,
  }),
  'creator' : IDL.Principal,
  'expiresAt' : Time,
  'creatorScore' : IDL.Nat,
  'code' : IDL.Text,
  'challengerScore' : IDL.Nat,
  'challenger' : IDL.Opt(IDL.Principal),
});
export const BattleChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'senderUsername' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'battleCode' : IDL.Text,
});
export const Tier = IDL.Variant({
  'bronze' : IDL.Null,
  'gold' : IDL.Null,
  'diamond' : IDL.Null,
  'platinum' : IDL.Null,
  'silver' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'xp' : IDL.Nat,
  'adFreeUntil' : Time,
  'username' : IDL.Text,
  'tier' : Tier,
  'level' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'xp' : IDL.Nat,
  'username' : IDL.Text,
  'tier' : Tier,
  'user' : IDL.Principal,
  'level' : IDL.Nat,
});
export const Streak = IDL.Record({
  'lastActiveDate' : IDL.Text,
  'currentStreak' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TournamentEntry = IDL.Record({
  'userId' : IDL.Principal,
  'timestamp' : Time,
  'tournamentId' : IDL.Nat,
  'pushupCount' : IDL.Nat,
});
export const WorkoutSession = IDL.Record({
  'exerciseId' : IDL.Nat,
  'userId' : IDL.Principal,
  'reps' : IDL.Nat,
  'timestamp' : Time,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptFriendRequest' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addDietEntry' : IDL.Func([DietEntry], [], []),
  'addExercise' : IDL.Func([Exercise], [], []),
  'addExerciseCategory' : IDL.Func([ExerciseCategory], [], []),
  'addWorkoutPlan' : IDL.Func([WorkoutPlan], [IDL.Nat], []),
  'addXp' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'canSeeAd' : IDL.Func([], [IDL.Bool], ['query']),
  'completeMission' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'xpGained' : IDL.Nat })],
      [],
    ),
  'completeWorkout' : IDL.Func([], [IDL.Record({ 'xpGained' : IDL.Nat })], []),
  'createBattle' : IDL.Func([IDL.Text], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createTournament' : IDL.Func(
      [IDL.Text, Time, Time, IDL.Nat, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'declineFriendRequest' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteWorkoutPlan' : IDL.Func([IDL.Nat], [], []),
  'enterTournament' : IDL.Func([IDL.Nat], [], []),
  'finalizeTournament' : IDL.Func([IDL.Nat], [], []),
  'getBattle' : IDL.Func([IDL.Text], [IDL.Opt(Battle)], ['query']),
  'getBattleChats' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BattleChatMessage)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(ExerciseCategory)], ['query']),
  'getDietEntries' : IDL.Func([], [IDL.Vec(DietEntry)], ['query']),
  'getDietEntriesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DietEntry)],
      ['query'],
    ),
  'getExercisesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Exercise)],
      ['query'],
    ),
  'getFriendsLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getMyFriendRequests' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getMyFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getMyStreak' : IDL.Func([], [Streak], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTournamentLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TournamentEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkoutPlans' : IDL.Func([], [IDL.Vec(WorkoutPlan)], ['query']),
  'getWorkoutSessions' : IDL.Func([], [IDL.Vec(WorkoutSession)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'joinBattle' : IDL.Func([IDL.Text], [], []),
  'logPushups' : IDL.Func([IDL.Nat], [], []),
  'logWorkoutSession' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'recordAdView' : IDL.Func([], [], []),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUserByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'sendBattleChat' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'sendFriendRequest' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitTournamentScore' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateMyBattleScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateStreak' : IDL.Func([IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DietEntry = IDL.Record({
    'id' : IDL.Nat,
    'fat' : IDL.Nat,
    'carbs' : IDL.Nat,
    'calories' : IDL.Nat,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'protein' : IDL.Nat,
  });
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Exercise = IDL.Record({
    'id' : IDL.Nat,
    'difficulty' : Difficulty,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'targetReps' : IDL.Nat,
    'category' : IDL.Text,
  });
  const ExerciseCategory = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const WorkoutExercise = IDL.Record({
    'name' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const WorkoutPlan = IDL.Record({
    'id' : IDL.Nat,
    'exercises' : IDL.Vec(WorkoutExercise),
    'description' : IDL.Text,
    'dayLabel' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Time = IDL.Int;
  const Battle = IDL.Record({
    'status' : IDL.Variant({
      'active' : IDL.Null,
      'finished' : IDL.Null,
      'waiting' : IDL.Null,
    }),
    'creator' : IDL.Principal,
    'expiresAt' : Time,
    'creatorScore' : IDL.Nat,
    'code' : IDL.Text,
    'challengerScore' : IDL.Nat,
    'challenger' : IDL.Opt(IDL.Principal),
  });
  const BattleChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'senderUsername' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'battleCode' : IDL.Text,
  });
  const Tier = IDL.Variant({
    'bronze' : IDL.Null,
    'gold' : IDL.Null,
    'diamond' : IDL.Null,
    'platinum' : IDL.Null,
    'silver' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'xp' : IDL.Nat,
    'adFreeUntil' : Time,
    'username' : IDL.Text,
    'tier' : Tier,
    'level' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'xp' : IDL.Nat,
    'username' : IDL.Text,
    'tier' : Tier,
    'user' : IDL.Principal,
    'level' : IDL.Nat,
  });
  const Streak = IDL.Record({
    'lastActiveDate' : IDL.Text,
    'currentStreak' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TournamentEntry = IDL.Record({
    'userId' : IDL.Principal,
    'timestamp' : Time,
    'tournamentId' : IDL.Nat,
    'pushupCount' : IDL.Nat,
  });
  const WorkoutSession = IDL.Record({
    'exerciseId' : IDL.Nat,
    'userId' : IDL.Principal,
    'reps' : IDL.Nat,
    'timestamp' : Time,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptFriendRequest' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addDietEntry' : IDL.Func([DietEntry], [], []),
    'addExercise' : IDL.Func([Exercise], [], []),
    'addExerciseCategory' : IDL.Func([ExerciseCategory], [], []),
    'addWorkoutPlan' : IDL.Func([WorkoutPlan], [IDL.Nat], []),
    'addXp' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'canSeeAd' : IDL.Func([], [IDL.Bool], ['query']),
    'completeMission' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'xpGained' : IDL.Nat })],
        [],
      ),
    'completeWorkout' : IDL.Func(
        [],
        [IDL.Record({ 'xpGained' : IDL.Nat })],
        [],
      ),
    'createBattle' : IDL.Func([IDL.Text], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createTournament' : IDL.Func(
        [IDL.Text, Time, Time, IDL.Nat, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'declineFriendRequest' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteWorkoutPlan' : IDL.Func([IDL.Nat], [], []),
    'enterTournament' : IDL.Func([IDL.Nat], [], []),
    'finalizeTournament' : IDL.Func([IDL.Nat], [], []),
    'getBattle' : IDL.Func([IDL.Text], [IDL.Opt(Battle)], ['query']),
    'getBattleChats' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BattleChatMessage)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(ExerciseCategory)], ['query']),
    'getDietEntries' : IDL.Func([], [IDL.Vec(DietEntry)], ['query']),
    'getDietEntriesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DietEntry)],
        ['query'],
      ),
    'getExercisesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Exercise)],
        ['query'],
      ),
    'getFriendsLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getMyFriendRequests' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getMyFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getMyStreak' : IDL.Func([], [Streak], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTournamentLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TournamentEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkoutPlans' : IDL.Func([], [IDL.Vec(WorkoutPlan)], ['query']),
    'getWorkoutSessions' : IDL.Func([], [IDL.Vec(WorkoutSession)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'joinBattle' : IDL.Func([IDL.Text], [], []),
    'logPushups' : IDL.Func([IDL.Nat], [], []),
    'logWorkoutSession' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'recordAdView' : IDL.Func([], [], []),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUserByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'sendBattleChat' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'sendFriendRequest' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitTournamentScore' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateMyBattleScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateStreak' : IDL.Func([IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };