/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DietEntry {
  'id' : bigint,
  'fat' : bigint,
  'carbs' : bigint,
  'calories' : bigint,
  'name' : string,
  'category' : string,
  'protein' : bigint,
}
export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface Exercise {
  'id' : bigint,
  'difficulty' : Difficulty,
  'name' : string,
  'description' : string,
  'targetReps' : bigint,
  'category' : string,
}
export interface ExerciseCategory { 'name' : string, 'description' : string }
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Tier = { 'bronze' : null } |
  { 'gold' : null } |
  { 'diamond' : null } |
  { 'platinum' : null } |
  { 'silver' : null };
export type Time = bigint;
export interface TournamentEntry {
  'userId' : Principal,
  'timestamp' : Time,
  'tournamentId' : bigint,
  'pushupCount' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'xp' : bigint,
  'adFreeUntil' : Time,
  'username' : string,
  'tier' : Tier,
  'level' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDietEntry' : ActorMethod<[DietEntry], undefined>,
  'addExercise' : ActorMethod<[Exercise], undefined>,
  'addExerciseCategory' : ActorMethod<[ExerciseCategory], undefined>,
  'addXp' : ActorMethod<[Principal, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'canSeeAd' : ActorMethod<[], boolean>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createTournament' : ActorMethod<
    [string, Time, Time, bigint, boolean],
    bigint
  >,
  'enterTournament' : ActorMethod<[bigint], undefined>,
  'finalizeTournament' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<ExerciseCategory>>,
  'getDietEntries' : ActorMethod<[], Array<DietEntry>>,
  'getDietEntriesByCategory' : ActorMethod<[string], Array<DietEntry>>,
  'getExercisesByCategory' : ActorMethod<[string], Array<Exercise>>,
  'getProfile' : ActorMethod<[Principal], UserProfile>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTournamentLeaderboard' : ActorMethod<[bigint], Array<TournamentEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'logPushups' : ActorMethod<[bigint], undefined>,
  'logWorkoutSession' : ActorMethod<[bigint, bigint], undefined>,
  'recordAdView' : ActorMethod<[], undefined>,
  'registerUser' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitTournamentScore' : ActorMethod<[bigint, bigint], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];