/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Battle {
  'status' : { 'active' : null } |
    { 'finished' : null } |
    { 'waiting' : null },
  'creator' : Principal,
  'expiresAt' : Time,
  'creatorScore' : bigint,
  'code' : string,
  'challengerScore' : bigint,
  'challenger' : [] | [Principal],
}
export interface BattleChatMessage {
  'id' : bigint,
  'text' : string,
  'senderUsername' : string,
  'sender' : Principal,
  'timestamp' : Time,
  'battleCode' : string,
}
export interface DietEntry {
  'id' : bigint,
  'fat' : bigint,
  'carbs' : bigint,
  'calories' : bigint,
  'name' : string,
  'category' : string,
  'protein' : bigint,
}
export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface Exercise {
  'id' : bigint,
  'difficulty' : Difficulty,
  'name' : string,
  'description' : string,
  'targetReps' : bigint,
  'category' : string,
}
export interface ExerciseCategory { 'name' : string, 'description' : string }
export interface LeaderboardEntry {
  'xp' : bigint,
  'username' : string,
  'tier' : Tier,
  'user' : Principal,
  'level' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface Streak { 'lastActiveDate' : string, 'currentStreak' : bigint }
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Tier = { 'bronze' : null } |
  { 'gold' : null } |
  { 'diamond' : null } |
  { 'platinum' : null } |
  { 'silver' : null };
export type Time = bigint;
export interface TournamentEntry {
  'userId' : Principal,
  'timestamp' : Time,
  'tournamentId' : bigint,
  'pushupCount' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'xp' : bigint,
  'adFreeUntil' : Time,
  'username' : string,
  'tier' : Tier,
  'level' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkoutExercise {
  'name' : string,
  'reps' : bigint,
  'sets' : bigint,
  'notes' : string,
}
export interface WorkoutPlan {
  'id' : bigint,
  'exercises' : Array<WorkoutExercise>,
  'description' : string,
  'dayLabel' : string,
}
export interface WorkoutSession {
  'exerciseId' : bigint,
  'userId' : Principal,
  'reps' : bigint,
  'timestamp' : Time,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptFriendRequest' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addDietEntry' : ActorMethod<[DietEntry], undefined>,
  'addExercise' : ActorMethod<[Exercise], undefined>,
  'addExerciseCategory' : ActorMethod<[ExerciseCategory], undefined>,
  'addWorkoutPlan' : ActorMethod<[WorkoutPlan], bigint>,
  'addXp' : ActorMethod<[Principal, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'canSeeAd' : ActorMethod<[], boolean>,
  'completeMission' : ActorMethod<[string], { 'xpGained' : bigint }>,
  'completeWorkout' : ActorMethod<[], { 'xpGained' : bigint }>,
  'createBattle' : ActorMethod<[string], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createTournament' : ActorMethod<
    [string, Time, Time, bigint, boolean],
    bigint
  >,
  'declineFriendRequest' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteWorkoutPlan' : ActorMethod<[bigint], undefined>,
  'enterTournament' : ActorMethod<[bigint], undefined>,
  'finalizeTournament' : ActorMethod<[bigint], undefined>,
  'getBattle' : ActorMethod<[string], [] | [Battle]>,
  'getBattleChats' : ActorMethod<[string], Array<BattleChatMessage>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<ExerciseCategory>>,
  'getDietEntries' : ActorMethod<[], Array<DietEntry>>,
  'getDietEntriesByCategory' : ActorMethod<[string], Array<DietEntry>>,
  'getExercisesByCategory' : ActorMethod<[string], Array<Exercise>>,
  'getFriendsLeaderboard' : ActorMethod<[], Array<UserProfile>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getMyFriendRequests' : ActorMethod<[], Array<Principal>>,
  'getMyFriends' : ActorMethod<[], Array<Principal>>,
  'getMyStreak' : ActorMethod<[], Streak>,
  'getProfile' : ActorMethod<[Principal], UserProfile>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTournamentLeaderboard' : ActorMethod<[bigint], Array<TournamentEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkoutPlans' : ActorMethod<[], Array<WorkoutPlan>>,
  'getWorkoutSessions' : ActorMethod<[], Array<WorkoutSession>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'joinBattle' : ActorMethod<[string], undefined>,
  'logPushups' : ActorMethod<[bigint], undefined>,
  'logWorkoutSession' : ActorMethod<[bigint, bigint], undefined>,
  'recordAdView' : ActorMethod<[], undefined>,
  'registerUser' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUserByUsername' : ActorMethod<[string], [] | [UserProfile]>,
  'sendBattleChat' : ActorMethod<[string, string], undefined>,
  'sendFriendRequest' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitTournamentScore' : ActorMethod<[bigint, bigint], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateMyBattleScore' : ActorMethod<[string, bigint], undefined>,
  'updateStreak' : ActorMethod<[string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];