/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    id: bigint;
    difficulty: Difficulty;
    name: string;
    description: string;
    targetReps: bigint;
    category: string;
}
export interface LeaderboardEntry {
    xp: bigint;
    username: string;
    tier: Tier;
    user: Principal;
    level: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface ExerciseCategory {
    name: string;
    description: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TournamentEntry {
    userId: Principal;
    timestamp: Time;
    tournamentId: bigint;
    pushupCount: bigint;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface DietEntry {
    id: bigint;
    fat: bigint;
    carbs: bigint;
    calories: bigint;
    name: string;
    category: string;
    protein: bigint;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface Battle {
    status: Variant_active_finished_waiting;
    creator: Principal;
    expiresAt: Time;
    creatorScore: bigint;
    code: string;
    challengerScore: bigint;
    challenger?: Principal;
}
export interface UserProfile {
    xp: bigint;
    adFreeUntil: Time;
    username: string;
    tier: Tier;
    level: bigint;
}
export enum Difficulty {
    easy = "easy",
    hard = "hard",
    medium = "medium"
}
export enum Tier {
    bronze = "bronze",
    gold = "gold",
    diamond = "diamond",
    platinum = "platinum",
    silver = "silver"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_active_finished_waiting {
    active = "active",
    finished = "finished",
    waiting = "waiting"
}
export interface BattleChatMessage {
    id: bigint;
    battleCode: string;
    sender: Principal;
    senderUsername: string;
    text: string;
    timestamp: bigint;
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDietEntry(entry: DietEntry): Promise<void>;
    addExercise(exercise: Exercise): Promise<void>;
    addExerciseCategory(category: ExerciseCategory): Promise<void>;
    addXp(user: Principal, xp: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    canSeeAd(): Promise<boolean>;
    createBattle(code: string): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createTournament(name: string, startDate: Time, endDate: Time, entryFee: bigint, isPaid: boolean): Promise<bigint>;
    enterTournament(tournamentId: bigint): Promise<void>;
    finalizeTournament(tournamentId: bigint): Promise<void>;
    getBattle(code: string): Promise<Battle | null>;
    getBattleChats(code: string): Promise<Array<BattleChatMessage>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategories(): Promise<Array<ExerciseCategory>>;
    getDietEntries(): Promise<Array<DietEntry>>;
    getDietEntriesByCategory(category: string): Promise<Array<DietEntry>>;
    getExercisesByCategory(category: string): Promise<Array<Exercise>>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getProfile(user: Principal): Promise<UserProfile>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTournamentLeaderboard(tournamentId: bigint): Promise<Array<TournamentEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    joinBattle(code: string): Promise<void>;
    logPushups(count: bigint): Promise<void>;
    logWorkoutSession(exerciseId: bigint, reps: bigint): Promise<void>;
    recordAdView(): Promise<void>;
    registerUser(username: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendBattleChat(code: string, text: string): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitTournamentScore(tournamentId: bigint, pushupCount: bigint): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateMyBattleScore(code: string, score: bigint): Promise<void>;
}
import type { Battle as _Battle, Difficulty as _Difficulty, Exercise as _Exercise, LeaderboardEntry as _LeaderboardEntry, StripeSessionStatus as _StripeSessionStatus, Tier as _Tier, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDietEntry(arg0: DietEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDietEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDietEntry(arg0);
            return result;
        }
    }
    async addExercise(arg0: Exercise): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExercise(to_candid_Exercise_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExercise(to_candid_Exercise_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addExerciseCategory(arg0: ExerciseCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExerciseCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExerciseCategory(arg0);
            return result;
        }
    }
    async addXp(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addXp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addXp(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async canSeeAd(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.canSeeAd();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.canSeeAd();
            return result;
        }
    }
    async createBattle(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBattle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBattle(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createTournament(arg0: string, arg1: Time, arg2: Time, arg3: bigint, arg4: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTournament(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTournament(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async enterTournament(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enterTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enterTournament(arg0);
            return result;
        }
    }
    async finalizeTournament(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.finalizeTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finalizeTournament(arg0);
            return result;
        }
    }
    async getBattle(arg0: string): Promise<Battle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBattle(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBattle(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(): Promise<Array<ExerciseCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getDietEntries(): Promise<Array<DietEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDietEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDietEntries();
            return result;
        }
    }
    async getDietEntriesByCategory(arg0: string): Promise<Array<DietEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDietEntriesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDietEntriesByCategory(arg0);
            return result;
        }
    }
    async getExercisesByCategory(arg0: string): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExercisesByCategory(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExercisesByCategory(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_UserProfile_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_UserProfile_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournamentLeaderboard(arg0: bigint): Promise<Array<TournamentEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentLeaderboard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentLeaderboard(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async joinBattle(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinBattle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinBattle(arg0);
            return result;
        }
    }
    async logPushups(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logPushups(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logPushups(arg0);
            return result;
        }
    }
    async logWorkoutSession(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logWorkoutSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWorkoutSession(arg0, arg1);
            return result;
        }
    }
    async recordAdView(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAdView();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAdView();
            return result;
        }
    }
    async registerUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitTournamentScore(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTournamentScore(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTournamentScore(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateMyBattleScore(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyBattleScore(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyBattleScore(arg0, arg1);
            return result;
        }
    }
    async getBattleChats(arg0: string): Promise<Array<BattleChatMessage>> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).getBattleChats(arg0);
                return result as Array<BattleChatMessage>;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).getBattleChats(arg0);
            return result as Array<BattleChatMessage>;
        }
    }
    async sendBattleChat(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).sendBattleChat(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).sendBattleChat(arg0, arg1);
            return result;
        }
    }
}

function from_candid_Battle_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Battle): Battle {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Exercise_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exercise): Exercise {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_LeaderboardEntry_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaderboardEntry): LeaderboardEntry {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Tier_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tier): Tier {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Battle]): Battle | null {
    return value.length === 0 ? null : from_candid_Battle_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xp: bigint;
    adFreeUntil: _Time;
    username: string;
    tier: _Tier;
    level: bigint;
}): {
    xp: bigint;
    adFreeUntil: Time;
    username: string;
    tier: Tier;
    level: bigint;
} {
    return {
        xp: value.xp,
        adFreeUntil: value.adFreeUntil,
        username: value.username,
        tier: from_candid_Tier_n15(_uploadFile, _downloadFile, value.tier),
        level: value.level
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    difficulty: _Difficulty;
    name: string;
    description: string;
    targetReps: bigint;
    category: string;
}): {
    id: bigint;
    difficulty: Difficulty;
    name: string;
    description: string;
    targetReps: bigint;
    category: string;
} {
    return {
        id: value.id,
        difficulty: from_candid_Difficulty_n22(_uploadFile, _downloadFile, value.difficulty),
        name: value.name,
        description: value.description,
        targetReps: value.targetReps,
        category: value.category
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xp: bigint;
    username: string;
    tier: _Tier;
    user: Principal;
    level: bigint;
}): {
    xp: bigint;
    username: string;
    tier: Tier;
    user: Principal;
    level: bigint;
} {
    return {
        xp: value.xp,
        username: value.username,
        tier: from_candid_Tier_n15(_uploadFile, _downloadFile, value.tier),
        user: value.user,
        level: value.level
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        active: null;
    } | {
        finished: null;
    } | {
        waiting: null;
    };
    creator: Principal;
    expiresAt: _Time;
    creatorScore: bigint;
    code: string;
    challengerScore: bigint;
    challenger: [] | [Principal];
}): {
    status: Variant_active_finished_waiting;
    creator: Principal;
    expiresAt: Time;
    creatorScore: bigint;
    code: string;
    challengerScore: bigint;
    challenger?: Principal;
} {
    return {
        status: from_candid_variant_n10(_uploadFile, _downloadFile, value.status),
        creator: value.creator,
        expiresAt: value.expiresAt,
        creatorScore: value.creatorScore,
        code: value.code,
        challengerScore: value.challengerScore,
        challenger: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.challenger))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    finished: null;
} | {
    waiting: null;
}): Variant_active_finished_waiting {
    return "active" in value ? Variant_active_finished_waiting.active : "finished" in value ? Variant_active_finished_waiting.finished : "waiting" in value ? Variant_active_finished_waiting.waiting : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bronze: null;
} | {
    gold: null;
} | {
    diamond: null;
} | {
    platinum: null;
} | {
    silver: null;
}): Tier {
    return "bronze" in value ? Tier.bronze : "gold" in value ? Tier.gold : "diamond" in value ? Tier.diamond : "platinum" in value ? Tier.platinum : "silver" in value ? Tier.silver : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
}): Difficulty {
    return "easy" in value ? Difficulty.easy : "hard" in value ? Difficulty.hard : "medium" in value ? Difficulty.medium : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n29(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exercise>): Array<Exercise> {
    return value.map((x)=>from_candid_Exercise_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaderboardEntry>): Array<LeaderboardEntry> {
    return value.map((x)=>from_candid_LeaderboardEntry_n25(_uploadFile, _downloadFile, x));
}
function to_candid_Difficulty_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Exercise_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Exercise): _Exercise {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Tier_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tier): _Tier {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    difficulty: Difficulty;
    name: string;
    description: string;
    targetReps: bigint;
    category: string;
}): {
    id: bigint;
    difficulty: _Difficulty;
    name: string;
    description: string;
    targetReps: bigint;
    category: string;
} {
    return {
        id: value.id,
        difficulty: to_candid_Difficulty_n3(_uploadFile, _downloadFile, value.difficulty),
        name: value.name,
        description: value.description,
        targetReps: value.targetReps,
        category: value.category
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xp: bigint;
    adFreeUntil: Time;
    username: string;
    tier: Tier;
    level: bigint;
}): {
    xp: bigint;
    adFreeUntil: _Time;
    username: string;
    tier: _Tier;
    level: bigint;
} {
    return {
        xp: value.xp,
        adFreeUntil: value.adFreeUntil,
        username: value.username,
        tier: to_candid_Tier_n33(_uploadFile, _downloadFile, value.tier),
        level: value.level
    };
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tier): {
    bronze: null;
} | {
    gold: null;
} | {
    diamond: null;
} | {
    platinum: null;
} | {
    silver: null;
} {
    return value == Tier.bronze ? {
        bronze: null
    } : value == Tier.gold ? {
        gold: null
    } : value == Tier.diamond ? {
        diamond: null
    } : value == Tier.platinum ? {
        platinum: null
    } : value == Tier.silver ? {
        silver: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
} {
    return value == Difficulty.easy ? {
        easy: null
    } : value == Difficulty.hard ? {
        hard: null
    } : value == Difficulty.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
